---
- name: change owner:group of Redmine directory
  file:
    path: "{{ redmine_dir }}"
    owner: "{{ redmine_dir_owner }}"
    group: "{{ redmine_dir_group }}"
    recurse: yes

- name: Check Passenger is installed
  command:
    test -f /usr/local/bin/passenger-install-apache2-module
  register:
    result
  failed_when: result.rc not in [0, 1]
  changed_when: false

- name: Install Passenger
  gem:
    name: passenger
    user_install: no
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: result.rc == 1

- name: Install apache2-module
  command:
    passenger-install-apache2-module --auto
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: result.rc == 1

- name: get apache2-module setting
  command:
    passenger-install-apache2-module --snippet
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register:
    passenger_snippet_vars
  changed_when: false

- name: Create redmine.conf
  template:
    src: redmine.conf
    dest: /etc/httpd/conf.d/redmine.conf

- name: Create deflate.conf
  copy:
    src: ../files/deflate.conf
    dest: /etc/httpd/conf.d/deflate.conf

- name: Restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
